title:              DataSEF
email:              data.sef23@gmail.com
description:        Skimmable Exploratory Framework
author:             DataSEF
baseurl:            ""
url:                "https://datasef.github.io"

# Social Profiles
twitter_username:   DataSEF
github_username:    DataSEF
facebook_username:  DataSEF
instagram_username:  
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
